import { createClient } from "@/lib/supabase/client";
import { DocumentSchemaType, DocumentUpdateSchemaType } from "./documentSchema";

export const fetchDocuments = async () => {
  const supabase = createClient();
  const { data, error } = await supabase.from("documents_view").select("*");

  if (error) throw new Error("Error fetching documents");

  return data;
};

export const fetchDocument = async (id: string) => {
  const supabase = createClient();
  const { data, error } = await supabase
    .from("documents_view")
    .select("*")
    .eq("id", id)
    .single();

  if (error) throw new Error("Error fetching documents");

  return data;
};

export const uploadFile = async (documentFile: File) => {
  const supabase = createClient();

  try {
    const {
      data: { session },
      error: sessionError,
    } = await supabase.auth.getSession();

    if (sessionError || !session?.access_token) {
      throw new Error("No user session found");
    }

    const token = session.access_token;

    const formData = new FormData();
    formData.append("file", documentFile);

    const res = await fetch("/api/documents/upload", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: formData,
    });

    const data = await res.json();

    if (!res.ok) {
      throw new Error(data?.error || "Upload failed");
    }

    return data;
  } catch (err: unknown) {
    console.error("Upload API error:", err);
    const message = err instanceof Error ? err.message : undefined;
    throw new Error(message || "API error");
  }
};

export const createDocument = async ({
  document,
  imageId,
}: {
  document: DocumentSchemaType;
  imageId: string;
}) => {
  const supabase = createClient();

  try {
    // id is generated by the database and tags aren't a column on
    // "documents" — both are intentionally excluded from the insert.
    const { id, tags, ...documentPayload } = document;
    void id;
    void tags;
    const { data: documentData, error: insertError } = await supabase
      .from("documents")
      .insert(documentPayload)
      .select()
      .single();

    if (insertError || !documentData) {
      throw new Error("Error creating your document");
    }

    const { error: updateError } = await supabase
      .from("files")
      .update({ status: "completed" })
      .eq("id", document.file_id);

    const { error: updateCoverError } = await supabase
      .from("images")
      .update({ owner_id: documentData.id, owner_type: "document" })
      .eq("id", imageId);

    if (updateError) {
      console.warn(
        `Document created but failed to update file status for file_id=${document.file_id}`,
      );
    }

    if (updateCoverError) {
      console.warn(
        `Document created but failed to update cover status for image_id=${imageId}`,
      );
    }

    return documentData;
  } catch (err: unknown) {
    console.error("createDocument error:", err);
    const message = err instanceof Error ? err.message : undefined;
    throw new Error(message || "Error creating document");
  }
};

export const updateDocument = async (
  updatedDocument: DocumentUpdateSchemaType,
) => {
  const { id, title, description, content_type, content_language } =
    updatedDocument;

  if (!id) throw new Error("Document id is required to update a document");

  const supabase = createClient();

  const { data, error } = await supabase
    .from("documents")
    .update({ title, description, content_type, content_language })
    .eq("id", id)
    .select()
    .single();

  if (error) throw new Error("Error updating your document");

  return data;
};
